# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: stripe-chp-payment

# Configuration variables
custom:
  secrets: ${file(secrets.json)}

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs18.x
  stage: devel
  # profile: personal
  # region: ap-southeast-1
  # Duration for CloudWatch log retention (default: forever)
  # logRetentionInDays: 14
  # Default memory size for functions (default: 1024MB)
  memorySize: 128
  # Note: API Gateway has a maximum timeout of 30 seconds
  timeout: 10
  environment:
    STRIPE_SECRET_KEY: ${self:custom.secrets.stripeSecretKey} # Stripe secret API key

# The `functions` block defines what code to deploy
functions:
  createCharge:
    handler: functions/createCharge.handler
    # The `events` block defines how to trigger the handler.createCharge code
    events:
      - http:
          path: chargeCard
          method: post
          cors: true
